=== Jacob-C-Smith/gschema/light-schema.json
{
    "$schema"      : "http://json-schema.org/schema",
    "title"        : "G10 Light",
    "type"         : "object",
    "description"  : "G10 light object definition",
    "properties"   : {
        "name"     : {
            "title"       : "name",
            "type"        : "string",
            "default"     : "Light",
            "minLength"   : 1,
            "maxLength"   : 255,
            "description" : "The name of the light"
        },
        "comment" : {
            "title"       : "comment",
            "type"        : "string",
            "default"     : "comment",
            "description" : "A comment that is ignored by G10"
        },
        "type"    : {
            "title"       : "type",
            "type"        : "string",
            "default"     : "point",
            "description" : "The type of the light",
            "enum": [
                "point",
                "directional",
                "spot",
                "area"
            ]
        },
        "location" : {
            "title"       : "location",
            "type"        : "array",
            "description" : "location of the light, < x, y, z >",
            "items"       : { "type" : "number" },
            "minItems"    : 3,
            "maxItems"    : 3,
            "default"     : [ 1.0, 1.0, 1.0 ]
        },
        "color"    : {
            "title"       : "color",
            "type"        : "array",
            "description" : "color of the light, < r, g, b >",
            "items"       : { "type" : "number", "maximum": 1.0, "minimum": 0.0 },
            "minItems"    : 3,
            "maxItems"    : 3,
            "default"     : [ 1.0, 1.0, 1.0 ]
        },
        "intensity":{
            "title" : "intensity",
            "type"  : "number",
            "description": "The intensity of the light in watts",
            "minimum": 0.0,
            "maximum": 100000.0,
            "default" : 60.0
        },
        "falloff" : {
            "title": "falloff",
            "type" : "number",
            "description": "The falloff distance of the light",
            "minimum": 0.01,
            "maximum": 1000.0,
            "default": 2
        },
        "direction" : {
            "title"       : "direction",
            "type"        : "array",
            "description" : "Direction of the light, < x, y, z >",
            "items"       : { "type" : "number"},
            "minItems"    : 3,
            "maxItems"    : 3,
            "default"     : [ 0.0, 0.0, -1.0 ]
        },
        "angle" : {
            "title"       : "angle",
            "type"        : "number",
            "description" : "The angle of the spot light cone, in degrees",
            "minimum"     : 0.0,
            "maximum"     : 180.0,
            "default"     : 30.0
        },
        "length" : {
            "title"       : "length",
            "type"        : "number",
            "description" : "The length of the area light cone",
            "minimum"     : 0.0,
            "maximum"     : 1000.0
        },
        "radius" : {
            "title"       : "radius",
            "type"        : "number",
            "description" : "The radius of the area light",
            "minimum"     : 0.0,
            "maximum"     : 1000.0
        }
    },
    "required"     : [ "name", "type", "location", "color", "intensity", "falloff" ]
}

=== Jacob-C-Smith/gschema/examples/light/area-light.json
{
    "$schema"  : "https://raw.githubusercontent.com/Jacob-C-Smith/G10-Schema/main/light-schema.json",
    "name"     : "Point light",
    "type"     : "area",
    "color"    : [ 1, 1, 1 ],
    "location" : [ 1, 1, 1 ],
    "intensity": 60,
    "falloff"  : 2,
    "direction": [ 1, 0, 0 ],
    "length"   : 1,
    "radius"   : 2
}

=== Jacob-C-Smith/gschema/examples/light/directional-light.json
{
    "$schema"  : "https://raw.githubusercontent.com/Jacob-C-Smith/G10-Schema/main/light-schema.json",
    "name"     : "Directional light",
    "type"     : "directional",
    "color"    : [ 1, 1, 1 ],
    "location" : [ 1, 1, 1 ],
    "intensity": 60,
    "falloff"  : 2,
    "direction": [ 0, 0, -1 ]
}

=== Jacob-C-Smith/gschema/examples/light/spot-light.json
{
    "$schema"  : "https://raw.githubusercontent.com/Jacob-C-Smith/G10-Schema/main/light-schema.json",
    "name"     : "Light",
    "type"     : "spot",
    "color"    : [ 1, 1, 1 ],
    "location" : [ 1, 1, 1 ],
    "intensity": 60,
    "falloff"  : 2,
    "angle"    : 30,
    "direction": [ 0, 1, 0 ]
}
