=== Jacob-C-Smith/gschema/schedule-schema.json
{
    "$schema"     : "http://json-schema.org/schema",
    "title"       : "G10 Schedule Object",
    "description" : "",
    "properties": {
        "name"        : {
            "title"       : "Name",
            "description" : "The name of the schedule",
            "type"        : "string",
            "default"     : "Schedule"
        },
        "main thread" : {
            "title"       : "Main thread",
            "description" : "The main thread of the schedule",
            "type"        : "string",
            "default"     : "Main thread"
        },
        "repeat"      : {
            "title"       : "Repeat",
            "description" : "Repeat the schedule?",
            "type"        : "boolean",
            "default"     : false
        },
        "threads"     :  {
            "title"       : "Threads",
            "description" : "List of threads",
            "type"        : "array",
            "uniqueItems" : true,
            "items"       : { "$ref": "#/$defs/thread" }
        }
    },
    "$defs" : {
        "task" : {
            "type" : "object",  
            "required": [ "task" ],
            "properties":{
                "task" : {
                    "title"       : "Task",
                    "description" : "The name of the task",
                    "type" : "string",
                    "enum" : [
                        "Input",
                        "UI",
                        "AI",
                        "Pre AI",
                        "Resolve Collisions",
                        "Update Forces",
                        "Move Objects",
                        "Animation",
                        "Render",
                        "Load Entity",
                        "Load Light Probe",
                        "Copy State",
                        "Server Recieve",
                        "Server Send",
                        "Audio"
                    ]
                },
                "wait thread" : {
                    "title" : "wait thread",
                    "description" : "The thread to wait on",
                    "type" : "string"
                },
                "wait task" : {
                    "title" : "wait task",
                    "description" : "The task to wait on",
                    "type" : "string"
                }
            }
        },
        "thread" : {
            "title": "Thread",
            "description": "",
            "type" : "object",
            "properties": {
                "name" : {
                    "title": "Name",
                    "description": "The name of the thread",
                    "type" : "string"
                },
                "description" : {
                    "title": "Descripton",
                    "description": "The descripton of the thread",
                    "type" : "string"
                },
                "tasks" : {
                    "title": "Tasks",
                    "description": "A list of tasks",
                    "type" : "array",
                    "uniqueItems": true,
                    "items": [
                        { "$ref" : "#/$defs/task" }
                    ]
                }
            }
        }
    }  
}

=== Jacob-C-Smith/gschema/examples/schedule/simple game loop.json
{
    "$schema": "../../schedule-schema.json",
    "name": "Schedule",
    "main thread": "Main thread",
    "repeat": false,
    "threads": [
        {
            "name": "Main thread",
            "description": "Main thread",
            "tasks": [
                {
                    "task": "Animation"
                },
                {
                    "task": ""
                }
            ]
        },
        {
            "name": "Render thread",
            "description": "Render thread",
            "tasks": [
                {
                    "task": "Render"
                }
            ]
        },
        {
            "name": "Worker 1",
            "description": "",
            "tasks": [
                {
                    "task": "Animation"
                },
                {
                    "task" : "AA"
                }
            ]
        }
    ]
    
}

=== Jacob-C-Smith/gschema/examples/schedule/game loop.json
{
    "name"         : "Game loop schedule",
    "threads"      : [
        {
            "name"        : "Render Thread",
            "description" : "Draws frame N-1",
            "tasks"       : [
                {
                    "task" : "Render"
                }
            ]
        },
        {
            "name"        : "Main Thread",
            "description" : "Game loop",
            "tasks"       : [
                {
                    "task"        : "Input",
                    "wait thread" : "Render Thread",
                    "wait task"   : "Render"
                },
                {
                    "task" : "UI"
                },
                {
                    "task"        : "AI",
                    "wait thread" : "Worker 2",
                    "wait task"   : "Pre AI"
                },
                {
                    "task" : "User Code"
                },
                {
                    "task" : "Resolve Collisions"
                },
                {
                    "task" : "Update Forces"
                },
                {
                    "task" : "Move Objects"
                },
                {
                    "task" : "Copy State"
                }
            ]
        },
        {
            "name"        : "Worker 1",
            "description" : "Audio and physics",
            "tasks"       : [
                {
                    "task"        : "Audio"
                },
                {
                    "task"        : "Resolve Collisions",
                    "wait thread" : "Main Thread",
                    "wait task"   : "User Code"
                },
                {
                    "task"        : "Update Forces"
                },
                {
                    "task"        : "Move Objects"
                }
            ]
        },
        {
            "name"        : "Worker 2",
            "description" : "Pre AI and physics",
            "tasks"       : [
                {
                    "task"        : "Pre AI"
                },
                {
                    "task"        : "Resolve Collisions",
                    "wait thread" : "Main Thread",
                    "wait task"   : "User Code"
                },
                {
                    "task"        : "Update Forces"
                },
                {
                    "task"        : "Move Objects"
                }
            ]
        },
        {
            "name"        : "Worker 3",
            "description" : "Server input and physics",
            "tasks"       : [
                {
                    "task"        : "Resolve Collisions",
                    "wait thread" : "Main Thread",
                    "wait task"   : "User Code"
                },
                {
                    "task"        : "Animation"
                },
                {
                    "task"        : "Move Objects"
                }
            ]
        },
        {
            "name"        : "Worker 4",
            "description" : "Server output and physics",
            "tasks"       : [
                {
                    "task"        : "Resolve Collisions",
                    "wait thread" : "Main Thread",
                    "wait task"   : "User Code"
                },
                {
                    "task"        : "Animation"
                },
                {
                    "task"        : "Move Objects"
                }
            ]
        }
    ],
    "main thread"  : "Main Thread",
    "repeat"       : true
}
